/** Party-friendly English prompts for Emoji Paths (no NSFW). */
export const WORDS_EN: string[] = [
  'coffee',
  'pizza',
  'bicycle',
  'rainbow',
  'library',
  'toothbrush',
  'vampire',
  'astronaut',
  'ice cream',
  'umbrella',
  'soccer',
  'dragon',
  'pirate',
  'robot',
  'sunflower',
  'train',
  'camera',
  'ghost',
  'crocodile',
  'balloon',
  'hamburger',
  'violin',
  'fireworks',
  'owl',
  'surfboard',
  'snowman',
  'cactus',
  'helicopter',
  'banana',
  'lion',
  'telescope',
  'fire truck',
  'penguin',
  'guitar',
  'castle',
  'shark',
  'elephant',
  'moon',
  'sunglasses',
  'trampoline',
  'octopus',
  'church',
  'ice skates',
  'popcorn',
  'dinosaur',
  'lighthouse',
  'koala',
  'trumpet',
  'volcano',
  'rabbit',
  'taxi',
  'butterfly',
  'hammer',
  'apple',
  'zebra',
  'subway',
  'pineapple',
  'ninja',
  'four-leaf clover',
  'turtle',
  'hotel',
  'orchestra',
  'shrimp',
  'skyscraper',
  'donut',
  'panda',
  'yacht',
  'hedgehog',
  'microphone',
  'hippo',
  'sandwich',
  'rocket',
  'kangaroo',
  'circus',
  'owl in a tree',
  'red carpet',
  'wilderness',
  'cartoon',
  'christmas tree',
  'rubber duck',
  'backpack',
  'fishing boat',
  'candy',
  'mountain peak',
  'key',
  'sandcastle',
  'night owl',
  'chocolate cake',
  'escalator',
  'blue whale',
  'camping',
  'wizard',
  'strawberry',
  'motorcycle',
  'rainbow sweater',
  'firework show',
  'ice cream truck',
  'librarian',
  'treasure chest',
  'roller skates',
  'morning coffee',
  'superhero',
  'pizza slice',
  'treehouse',
  'northern lights',
  'beach ball',
  'haunted house',
  'newspaper',
  'four-legged friend',
  'red tulip',
  'rainy street',
  'yellow taxi',
  'winter sports',
  'music festival',
  'beach chair',
  'chocolate milk',
  'tiny robot',
  'huge elephant',
  'fast bike',
  'calm lake',
  'tall mountain',
  'hot soup',
  'cold ice cream',
  'happy dog',
  'sleepy cat',
  'angry penguin',
  'dancing bear',
  'flying carpet',
  'magic mirror',
  'hidden treasure',
  'broken umbrella',
  'luxury yacht',
  'cheeky monkey',
  'tired student',
  'hungry shark',
  'curious owl',
  'brave knight',
  'friendly dragon',
  'wild horse',
  'quiet library',
  'loud concert',
  'soft pillow',
  'sharp sword',
  'round pizza',
  'long train ride',
  'short vacation',
  'big family',
  'small village',
  'old radio',
  'new phone',
  'blue sky',
  'green forest',
  'yellow sun',
  'black night',
]
