/** Party-friendly Swedish prompts for Emoji Paths (no NSFW). */
export const WORDS_SV: string[] = [
  'kaffe',
  'pizza',
  'cykel',
  'regnbåge',
  'bibliotek',
  'tandborste',
  'vampyr',
  'astronaut',
  'glass',
  'paraply',
  'fotboll',
  'drake',
  'pirat',
  'robot',
  'solros',
  'tåg',
  'kamera',
  'spöke',
  'krokodil',
  'ballong',
  'hamburgare',
  'fiol',
  'fyrverkeri',
  'uggla',
  'surfbräda',
  'snögubbe',
  'kaktus',
  'helikopter',
  'banan',
  'lejon',
  'teleskop',
  'brandbil',
  'pingvin',
  'gitarr',
  'slott',
  'haj',
  'elefant',
  'måne',
  'solglasögon',
  'trampolin',
  'bläckfisk',
  'kyrka',
  'skridskor',
  'popcorn',
  'dinosaurier',
  'fyr',
  'koala',
  'trumpet',
  'vulkan',
  'kanin',
  'taxi',
  'fjäril',
  'hammare',
  'äpple',
  'zebra',
  'tunnelbana',
  'ananas',
  'ninja',
  'fyrklöver',
  'sköldpadda',
  'hotell',
  'orkester',
  'räka',
  'skyskrapa',
  'munk',
  'panda',
  'yacht',
  'igelkott',
  'mikrofon',
  'flodhäst',
  'sandwich',
  'raket',
  'känguru',
  'cirkus',
  'uggla i träd',
  'röd matta',
  'vildmark',
  'tecknad film',
  'julgran',
  'badanka',
  'ryggsäck',
  'fiskebåt',
  'godis',
  'bergstopp',
  'nyckel',
  'trumpetare',
  'sandslott',
  'nattuggla',
  'chokladkaka',
  'rulltrappa',
  'blåval',
  'camping',
  'trollkarl',
  'jordgubbe',
  'motorcykel',
  'regnbågströja',
  'fyrverkerishow',
  'glassbil',
  'bibliotekarie',
  'skattkista',
  'rullskridskor',
  'morgonkaffe',
  'superhjälte',
  'pizzaslice',
  'trädhus',
  'norrsken',
  'badboll',
  'spökhus',
  'tidning',
  'fyrbent vän',
  'röd tulpan',
  'gata i regn',
  'gul taxi',
  'vintersport',
  'musikfestival',
  'strandstol',
  'chokladmjölk',
  'liten robot',
  'stor elefant',
  'snabb cykel',
  'lugn sjö',
  'högt berg',
  'varm soppa',
  'kall glass',
  'lycklig hund',
  'sömnig katt',
  'arg pingvin',
  'dansande björn',
  'flygande matta',
  'magisk spegel',
  'gömd skatt',
  'trasig paraply',
  'lyxig yacht',
  'busig apa',
  'trött student',
  'hungrig haj',
  'nyfiken uggla',
  'modig riddare',
  'snäll drake',
  'vild häst',
  'tyst bibliotek',
  'högljudd konsert',
  'mjuk kudde',
  'vasst svärd',
  'rund pizza',
  'lång tågresa',
  'kort semester',
  'stor familj',
  'liten by',
  'gammal radio',
  'ny telefon',
  'blå himmel',
  'grön skog',
  'gul sol',
  'svart natt',
]
